### ISSUE TITLE
Rename repo's name at DockerHub

### ISSUE THREAD

**Issue by sawadashota** [ory/kratos-selfservice-ui-node#10]
Repository's name at DockerHub looks old.
It should be `kratos-selfservice-ui-node`.
https://hub.docker.com/r/oryd/hive-selfservice-ui-node

**Comment by aeneasr** [comment]
Thanks! Done: https://hub.docker.com/r/oryd/kratos-selfservice-ui-node

**Comment by sawadashota** [comment]
Thanks!
