### ISSUE TITLE
kratos hydra-integration flow doesn't work on chrome, works on ff

### ISSUE THREAD

**Issue by ericb-summit** [ory/kratos-selfservice-ui-node#109]
**Describe the bug**

The existing hydra-integration branch only works when accessing the oauth2 client page through firefox not chrome.  On Chrome, an error is presented after the sign in flow instead of the being forwarded to the callback URL.

**To Reproduce**

Start the hydra-integration components and access http://127.0.0.1:5555 from chromium or similar.

**Expected behavior**

You should get the callback URL with the tokens.

**Environment**

- Ubuntu 20 for my colleague and me, but pretty sure there was discussion elsewhere that others had this issue as well

**Additional context**

Honestly I feel no urgency to fix this.  Creating this mostly to track the issue so someone gets to it eventually.  (I have a feeling that's gonna be me).

**Comment by aeneasr** [comment]
Might be relevant: https://github.com/ory/kratos/blob/master/docs/docs/debug/csrf.mdx#samesite-attribute

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
