### ISSUE TITLE
Potential issue with response cache

### ISSUE THREAD

**Issue by harnash** [ory/kratos-selfservice-ui-node#121]
**Describe the bug**

Whenever frontend is calling node.js backend and there is an error (validation) user get's redirected to the previous page. With this response it should get info about errors occurred during validation. However I can see that those responses are cached and returned plain form data without any errors whatsoever. Disabling cache on node.js end seems to help but it looks like a hacky way to fix the problem.

**To Reproduce**

1. Go to registration form.
2. Enter any data into form fields except password which fill in with some well known pass phrase like `secret`.
3. Form will be reloaded but no error is shown in the UI.
4. Check responses `Age` header to see which one gets cached.

**Expected behavior**

Responses should be properly varied and not cached only based on request params (not sure how it works currently).

**Environment**

- Version: v0.5.0 - v0.6.0
- Environment: kubernetes

**Additional context**
My hacky fix looks like this https://github.com/Wikia/kratos-selfservice-ui-node/commit/a02c9bfc40aac4539bf48a1a486d263545dd9a39

**Comment by aeneasr** [comment]
I don’t believe that the node client has any caching at all, plus we have lots of e2e tests using this repository which check the error behavior and have not seen any breaking tests. Are you sure this is indeed what is happening? Sometimes one can get confused with the URLs, query params, and so on.

**Comment by harnash** [comment]
Here is a WAR file from the app running official Ory image: https://ufile.io/9ualdxl2 (check the last request/response)
Here is a WAR file from the "hacked" version with no cache: https://ufile.io/7remnv9y
I don't think Node Client is the culprit but it seems that NodeJS server that serves the responses to the user's browser is causing this? Not an expert on NodeJS that is why I'm asking if that could be the case

**Comment by aeneasr** [comment]
Isn’t WAR Java? 🤔 Unfortunately I have no experience with Java and can only say that this node client in this repository works fine. Kratos itself is not setting cache headers so maybe your client (Java) is caching something per default but you would have to check the docs of the lib you’re using.

**Comment by harnash** [comment]
😞 Sorry. I meant `HAR` files for use with Developer Tool in browsers :-( You can import the whole session and  inspect each requests as they were invoked in my browser during user registration.

**Comment by aeneasr** [comment]
Ah got it, that makes more sense :) I’m currently on vacation without laptop so not able to check the HAR file but will check when I’m back in the office next week!

**Comment by aeneasr** [comment]
Ah got it, that makes more sense :) I’m currently on vacation without laptop so not able to check the HAR file but will check when I’m back in the office next week!

**Comment by aeneasr** [comment]
Never had time to check this properly. Is this still an issue? We have redeveloped and also deployed this app as part of Ory Cloud and have not had any issues with it so far, so I'm wondering if this is still problematic?

**Comment by harnash** [comment]
I think we can close since it is elusive and we do not rely on this app anymore so I can't confirm if that still happens. We can always reopen if we encounter this issue again.
