### ISSUE TITLE
logout page not found

### ISSUE THREAD

**Issue by david972** [ory/kratos-selfservice-ui-node#134]
**Describe the bug**
The logout link on all pages refer to a page that does not exists

**To Reproduce**

1. login
2. Click logout

**Expected behavior**

Expect to log out and redirected on the after logout page

**Environment**

- Version: v0.6.3-alpha.1
- Environment: Docker/kubernetes

**Additional context**

**Comment by aeneasr** [comment]
Are you using the master branch from this repo?

**Comment by david972** [comment]
from this repo no
but from kratos yes

**Comment by aeneasr** [comment]
Ok please use master from both or versioned from both but not a mix :)

**Comment by david972** [comment]
ok noted

**Comment by david972** [comment]
ok much better
