### ISSUE TITLE
Face Bug At Login

### ISSUE THREAD

**Issue by FlockOfBirdz** [ory/kratos-selfservice-ui-node#139]
**Getting error when want to login**

I have cloned your self-ui app, ran quickstart kratos as docs said, exported global variables, ran "make quickstart-dev"  and ran "npm build" to install node modules. then I ran npm start and project created sucessfuly. When project started it gets login forms from server but afterwards when i submit login btn I face below bug from self-ui app:

> (node:27206) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
>     at createError (/home/ali/Desktop/edited-kratos-selfservice-ui-node/node_modules/axios/lib/core/createError.js:16:15)
>     at settle (/home/ali/Desktop/edited-kratos-selfservice-ui-node/node_modules/axios/lib/core/settle.js:17:12)
>     at IncomingMessage.handleStreamEnd (/home/ali/Desktop/edited-kratos-selfservice-ui-node/node_modules/axios/lib/adapters/http.js:260:11)
>     at IncomingMessage.emit (events.js:326:22)
>     at endReadableNT (_stream_readable.js:1241:12)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> (node:27206) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 28) 

and this error from Kratos:

> kratos_1                      | time=2021-07-14T08:32:43Z level=info msg=started handling request func=github.com/ory/x/reqlog.(*Middleware).ServeHTTP file=/go/pkg/mod/github.com/ory/x@v0.0.238/reqlog/middleware.go:131 http_request=map[headers:map[accept:application/json, text/plain, */* cookie:i18n_redirected=fa; aHR0cDovLzEyNy4wLjAuMTozMDAwLw_csrf_token=xjOmfnudP7DUD0z89HQgG9OtQbdgisAy/Yt+2cJi6Wg=; aHR0cDovLzEyNy4wLjAuMTo0NDMzLw_csrf_token=FE9C1OR48FnZkl6uFZTpTSKjCdSp+pGjipf4333J5ss=; data={%22id%22:%223235ab92-2865-43c6-8a18-13270eec0313%22%2C%22type%22:%22api%22%2C%22expires_at%22:%222021-07-03T10:38:30.095510129Z%22%2C%22issued_at%22:%222021-07-03T10:28:30.095510129Z%22%2C%22request_url%22:%22http://127.0.0.1:4433/self-service/login/api%22%2C%22ui%22:{%22action%22:%22http://127.0.0.1:4433/self-service/login?flow=3235ab92-2865-43c6-8a18-13270eec0313%22%2C%22method%22:%22POST%22%2C%22nodes%22:[{%22type%22:%22input%22%2C%22group%22:%22default%22%2C%22attributes%22:{%22name%22:%22csrf_token%22%2C%22type%22:%22hidden%22%2C%22value%22:%22%22%2C%22required%22:true%2C%22disabled%22:false}%2C%22messages%22:null%2C%22meta%22:{}}%2C{%22type%22:%22input%22%2C%22group%22:%22password%22%2C%22attributes%22:{%22name%22:%22password_identifier%22%2C%22type%22:%22text%22%2C%22value%22:%22%22%2C%22required%22:true%2C%22disabled%22:false}%2C%22messages%22:null%2C%22meta%22:{%22label%22:{%22id%22:1070004%2C%22text%22:%22ID%22%2C%22type%22:%22info%22}}}%2C{%22type%22:%22input%22%2C%22group%22:%22password%22%2C%22attributes%22:{%22name%22:%22password%22%2C%22type%22:%22password%22%2C%22required%22:true%2C%22disabled%22:false}%2C%22messages%22:null%2C%22meta%22:{%22label%22:{%22id%22:1070001%2C%22text%22:%22Password%22%2C%22type%22:%22info%22}}}%2C{%22type%22:%22input%22%2C%22group%22:%22password%22%2C%22attributes%22:{%22name%22:%22method%22%2C%22type%22:%22submit%22%2C%22value%22:%22password%22%2C%22disabled%22:false}%2C%22messages%22:null%2C%22meta%22:{%22label%22:{%22id%22:1010001%2C%22text%22:%22Sign%20in%22%2C%22type%22:%22info%22%2C%22context%22:{}}}}]}%2C%22forced%22:false}; ory_kratos_session=MTYyNjI1MTIwNnxEdi1CQkFFQ180SUFBUkFCRUFBQVJfLUNBQUVHYzNSeWFXNW5EQThBRFhObGMzTnBiMjVmZEc5clpXNEdjM1J5YVc1bkRDSUFJR1JLVmtKR1ZFWmlOVWRXWVZscmNXRm5WVXBGZDFOcmRsTnVTekpyT1ZCT3z_UP5VRPCy4Ej2WxffQUZwFgIgS0Tc0XefztVTHLdVuA== user-agent:axios/0.21.1] host:127.0.0.1:4433 method:GET path:/self-service/logout/browser query:<nil> remote:172.20.0.1:47356 scheme:http]

I am new to typescript and go so I do not know what this errors mean, but I guess there is something with my ts version or node_modules.

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.

**Comment by FlockOfBirdz** [comment]
Thanks for your response @aeneasr . I tried to fix the structure of my issue with following information. Your help worth a million to me.

**Describe the bug**

When project started it gets login forms as expected from the Kratos server but afterwards when i submit login btn I face an error

**To Reproduce**

I followed bellow steps:

- cloned self-ui app
- ran quickstart kratos command
   - docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate
- exported global variables
- "make quickstart-dev" 
- "npm install" to install node modules
- npm start and project created sucessfuly. 

**Expected behavior**

Kratos should sends me back the result of login flow according to my credentials. but before getting anything from kratos app stops working with an error.

**Environment**

- Version:  v0.7.0alpha
- Environment: Linux 20.04
- typescript 3.9.9
- ts-node 9.1.1
- ts-node-dev 1.1.8

**Additional context**

Log from Self-UI app:

> npm start
> 
> > kratos-selfservice-ui-node@0.0.1 start /home/ali/Desktop/edited-kratos-selfservice-ui-node
> > ts-node-dev --watch public,views --respawn src/index.ts
> 
> [INFO] 13:01:41 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 3.9.9)
> Listening on http://0.0.0.0:4455
> Security mode: cookie
> GET /login 302 46 - 6.561 ms
> (node:27206) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
>     at createError (/home/ali/Desktop/edited-kratos-selfservice-ui-node/node_modules/axios/lib/core/createError.js:16:15)
>     at settle (/home/ali/Desktop/edited-kratos-selfservice-ui-node/node_modules/axios/lib/core/settle.js:17:12)
>     at IncomingMessage.handleStreamEnd (/home/ali/Desktop/edited-kratos-selfservice-ui-node/node_modules/axios/lib/adapters/http.js:260:11)
>     at IncomingMessage.emit (events.js:326:22)
>     at endReadableNT (_stream_readable.js:1241:12)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> (node:27206) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:27206) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 

Log from Kratos server:

> kratos_1 | time=2021-07-14T08:32:43Z level=info msg=started handling request func=github.com/ory/x/reqlog.(*Middleware).ServeHTTP file=/go/pkg/mod/github.com/ory/x@v0.0.238/reqlog/middleware.go:131 http_request=map[headers:map[accept:application/json, text/plain, / cookie:i18n_redirected=fa; aHR0cDovLzEyNy4wLjAuMTozMDAwLw_csrf_token=xjOmfnudP7DUD0z89HQgG9OtQbdgisAy/Yt+2cJi6Wg=; aHR0cDovLzEyNy4wLjAuMTo0NDMzLw_csrf_token=FE9C1OR48FnZkl6uFZTpTSKjCdSp+pGjipf4333J5ss=; data={%22id%22:%223235ab92-2865-43c6-8a18-13270eec0313%22%2C%22type%22:%22api%22%2C%22expires_at%22:%222021-07-03T10:38:30.095510129Z%22%2C%22issued_at%22:%222021-07-03T10:28:30.095510129Z%22%2C%22request_url%22:%22http://127.0.0.1:4433/self-service/login/api%22%2C%22ui%22:{%22action%22:%22http://127.0.0.1:4433/self-service/login?flow=3235ab92-2865-43c6-8a18-13270eec0313%22%2C%22method%22:%22POST%22%2C%22nodes%22:[{%22type%22:%22input%22%2C%22group%22:%22default%22%2C%22attributes%22:{%22name%22:%22csrf_token%22%2C%22type%22:%22hidden%22%2C%22value%22:%22%22%2C%22required%22:true%2C%22disabled%22:false}%2C%22messages%22:null%2C%22meta%22:{}}%2C{%22type%22:%22input%22%2C%22group%22:%22password%22%2C%22attributes%22:{%22name%22:%22password_identifier%22%2C%22type%22:%22text%22%2C%22value%22:%22%22%2C%22required%22:true%2C%22disabled%22:false}%2C%22messages%22:null%2C%22meta%22:{%22label%22:{%22id%22:1070004%2C%22text%22:%22ID%22%2C%22type%22:%22info%22}}}%2C{%22type%22:%22input%22%2C%22group%22:%22password%22%2C%22attributes%22:{%22name%22:%22password%22%2C%22type%22:%22password%22%2C%22required%22:true%2C%22disabled%22:false}%2C%22messages%22:null%2C%22meta%22:{%22label%22:{%22id%22:1070001%2C%22text%22:%22Password%22%2C%22type%22:%22info%22}}}%2C{%22type%22:%22input%22%2C%22group%22:%22password%22%2C%22attributes%22:{%22name%22:%22method%22%2C%22type%22:%22submit%22%2C%22value%22:%22password%22%2C%22disabled%22:false}%2C%22messages%22:null%2C%22meta%22:{%22label%22:{%22id%22:1010001%2C%22text%22:%22Sign%20in%22%2C%22type%22:%22info%22%2C%22context%22:{}}}}]}%2C%22forced%22:false}; ory_kratos_session=MTYyNjI1MTIwNnxEdi1CQkFFQ180SUFBUkFCRUFBQVJfLUNBQUVHYzNSeWFXNW5EQThBRFhObGMzTnBiMjVmZEc5clpXNEdjM1J5YVc1bkRDSUFJR1JLVmtKR1ZFWmlOVWRXWVZscmNXRm5WVXBGZDFOcmRsTnVTekpyT1ZCT3z_UP5VRPCy4Ej2WxffQUZwFgIgS0Tc0XefztVTHLdVuA== user-agent:axios/0.21.1] host:127.0.0.1:4433 method:GET path:/self-service/logout/browser query: remote:172.20.0.1:47356 scheme:http]

**Comment by aeneasr** [comment]
I think this could help: https://www.ory.sh/kratos/docs/debug/csrf
