### ISSUE TITLE
Reiterate Design

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos-selfservice-ui-node#16]
especially error messages on the login/registration screen need to be designed:
![Screenshot from 2020-01-21 12-08-24](https://user-images.githubusercontent.com/5354445/72800645-20926b80-3c48-11ea-887c-fa7326f4e3c5.png)

**Comment by jfcurran** [comment]
![error message](https://user-images.githubusercontent.com/24988314/72805181-94d20c80-3c52-11ea-8663-2abc73929630.jpg)

example error message - screen can be found within [figma](https://www.figma.com/file/TaexsOBde1mQoShxj6vJ47/ORY-Console-UI?node-id=2%3A24)

**Comment by aeneasr** [comment]
@jfcurran can you spend 30-60 minutes on a redesign of this particular app as soon as possible? This is a blocker for @zepatrik at the moment (and for me because I want to document these screens with screenshots).

We want the design to look as good as possible when releasing the first demo!
