### ISSUE TITLE
Redirect loop with kratos-selfservice-ui-node and ory platform

### ISSUE THREAD

**Issue by till** [ory/kratos-selfservice-ui-node#167]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hi,

for context, we are evaluating kratos, oathkeeper and keto currently. So I cloned the example repository when I ran into cookie issues with the hosted UI. I am currently facing a redirect loop.

### Reproducing the bug

What I've done so far:

I've cloned your repository, built the docker image (`make docker`) and deployed it on a public URL. The only environment variable I set is `KRATOS_PUBLIC_URL: https://XXX.projects.oryapis.com/api/kratos/public`.

Then I went into the Console (your UI) and configured the custom links for login, registration, recovery, etc..

The project starts up, and I get redirect to `/welcome`.

Whenever I click any of the buttons for login, etc. my browser eventually gives up with a "too many redirects" error.

### Relevant log output

To repro on the command line:

```shell
$ curl -L https://my-app.example.org/login
curl: (47) Maximum (50) redirects followed


# or more detailed:

$ curl -v -L https://my-app.example.org/login
*   Trying 5.57.43.202...
* TCP_NODELAY set
* Connected to my-app.example.org (5.57.43.202) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=my-app.example.org
*  start date: Feb  3 18:32:25 2022 GMT
*  expire date: May  4 18:32:24 2022 GMT
*  subjectAltName: host "my-app.example.org" matched cert's "my-app.example.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fab5080d600)
> GET /login HTTP/2
> Host: my-app.example.org
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 303 
< content-type: text/plain; charset=utf-8
< date: Thu, 03 Feb 2022 19:48:57 GMT
< location: https://XXX.projects.oryapis.com/api/kratos/public/self-service/login/browser?aal=&refresh=&return_to=
< vary: Accept
< x-powered-by: Express
< content-length: 149
< 
* Ignoring the response-body
* Connection #0 to host my-app.example.org left intact
* Issue another request to this URL: 'https://XXX.projects.oryapis.com/api/kratos/public/self-service/login/browser?aal=&refresh=&return_to='
*   Trying 104.18.13.126...
* TCP_NODELAY set
* Connected to XXX.projects.oryapis.com (104.18.13.126) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=oryapis.com
*  start date: Jan  9 00:00:00 2022 GMT
*  expire date: Apr  9 23:59:59 2022 GMT
*  subjectAltName: host "XXX.projects.oryapis.com" matched cert's "*.projects.oryapis.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fab5080d600)
> GET /api/kratos/public/self-service/login/browser?aal=&refresh=&return_to= HTTP/2
> Host: XXX.projects.oryapis.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 303 
< date: Thu, 03 Feb 2022 19:48:57 GMT
< content-type: text/html; charset=utf-8
< content-length: 103
< location: https://my-app.example.org/login?flow=72b79c56-0af8-49ae-a91c-cbba28733501
< cache-control: private, no-cache, no-store, must-revalidate
< set-cookie: csrf_token_a7d567194e5d40721c3e0a70dba7fcc523fb7ac0cc53b288b4b9a33eb2feadcd=JozvwPabFKYlEbNqprABjOF8sorsnhcUFrz9rEvZf14=; Path=/; Domain=XXX.projects.oryapis.com; Max-Age=31536000; HttpOnly; Secure; SameSite=Lax
< vary: Origin,Cookie
< x-envoy-upstream-service-time: 101
< permissions-policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), usb=()
< referrer-policy: strict-origin-when-cross-origin
< x-content-type-options: nosniff
< x-frame-options: DENY
...
```
```


### Relevant configuration

```yml
KRATOS_PUBLIC_URL: https://XXX.projects.oryapis.com/api/kratos/public
```

### Version

master

### On which operating system are you observing this issue?

Ory Cloud

### In which environment are you deploying?

Docker Compose

### Additional Context

Strictly speaking, I am deploying the app on Docker Swarm. But it's very similar to Docker Compose.

**Comment by aeneasr** [comment]
Unfortunately, both apps must be deployed on the same top-level-domain for this to work properly, as you need to have the cookie avilable under the same common domain. You can use the new custom domain feature of [Ory Cloud](https://www.ory.sh/docs/guides/custom-domains/). This is only available on a paid plan but we have a program where you [get that free for a year](https://share-eu1.hsforms.com/1KWJxgKzNQWOjR9r5blC41wextgn)

Alternatively, you can use the Ory Proxy to "hack" the domain / cookie. More on this topic with a NodeJS example is here: https://www.ory.sh/docs/start-building/server-side-web-app#expressjs--nodejs

**Comment by till** [comment]
@aeneasr Thank you! Didn't expect anyone to reply so late in the day, I filled out the form and will take a look at the proxy as well tomorrow.

**Comment by aeneasr** [comment]
Cool :) If you don't hear from us or have any other question feel free to post here :)

**Comment by till** [comment]
Just glanced over the example. The proxy looks similar to what oathkeeper would be doing?

**Comment by aeneasr** [comment]
Yes, we have simplified a lot and also changed some things for Cookies to work. The goal is for Oathkeeper to become the Ory Proxy, but we have this on the back burner currently as there is too much work going on with Kratos, Keto and Cloud

**Comment by till** [comment]
I played around with the proxy, and that seems like a good way to continue to test, however, it doesn't seem to recognize the SDK url:

```yaml
  proxy:
    image: oryd/ory
    environment:
      ORY_SDK_URL: https://XXX.projects.oryapis.com
    command: proxy --sdk-url=https://XXX.projects.oryapis.com http://tasks.ui:3000 https://public-url.example.org
```

I actually tried both, the proxy is running - but the error below occurs:

```
time=2022-02-04T09:42:07Z level=info audience=application service_name=ory/proxy service_version=v0.1.22 started_at=2022-02-04 09:42:07.834849232 +0000 UTC m=+0.022366883
time=2022-02-04T09:42:07Z level=info msg=ES256 JSON Web Key generation completed. audience=application completed_at=2022-02-04 09:42:07.835141595 +0000 UTC m=+0.022659225 service_name=ory/proxy service_version=v0.1.22
time=2022-02-04T09:42:07Z level=info msg=Starting the http reverse proxy on: :4000 audience=application service_name=ory/proxy service_version=v0.1.22
time=2022-02-04T09:42:07Z level=info msg=To access your application through the Ory Proxy, open:
	https://public-url.example.org audience=application service_name=ory/proxy service_version=v0.1.22
```

Do I need to use another URL? Like one of the API URLs instead of the endpoint?

The error is:

```json
{"error":{"code":404,"status":"Not Found","request":"b90a1aff-74ce-4681-8234-d8419f0d8a81","reason":"The requested Ory Cloud Project does not exist. Please ensure your custom domain or Ory Cloud Project Slug are correct.","message":"project not found"}}
```

Can you, by chance, lookup the request?

**Comment by aeneasr** [comment]
Could you check to use the latest version of the Ory CLI? So: ` image: oryd/ory:v0.1.22`

**Comment by zepatrik** [comment]
The logs say `v0.1.22`. I suspect that this is not setting the right host before forwarding? Therefore we assume it is a CNAME, but we don't find it https://github.com/ory/cli/blob/93b27f5028632dea9e22b6e46beccd3f280ef4c0/cmd/cloud/proxy/common.go#L95-L112

**Comment by till** [comment]
Been scanning the code, is there a debug flag? I tried to set `LOG_LEVEL=trace`, but that doesn't seem to apply to the proxy command.

**Comment by aeneasr** [comment]
I just tried the example at https://www.ory.sh/docs/start-building/server-side-web-app#expressjs--nodejs and it worked. From the env vars, everything looks correct. Here is my proxy log:

```
% ory proxy --port 4000 http://localhost:8000/ --sdk-url=https://playground.projects.oryapis.com

INFO[2022-02-04T11:50:46+01:00]                                               audience=application service_name=ory/proxy service_version=v0.1.16 started_at=2022-02-04 11:50:46.95363 +0100 CET m=+0.016548530
INFO[2022-02-04T11:50:46+01:00] ES256 JSON Web Key generation completed.      audience=application completed_at=2022-02-04 11:50:46.953787 +0100 CET m=+0.016705970 service_name=ory/proxy service_version=v0.1.16
INFO[2022-02-04T11:50:46+01:00] Starting the http reverse proxy on: :4000     audience=application service_name=ory/proxy service_version=v0.1.16
INFO[2022-02-04T11:50:46+01:00] To access your application through the Ory Proxy, open:

	http://localhost:4000  audience=application service_name=ory/proxy service_version=v0.1.16
^CINFO[2022-02-04T11:50:57+01:00] http reverse proxy was shutdown gracefully    audience=application service_name=ory/proxy service_version=v0.1.16
```

**Comment by till** [comment]
I rethought my objective and with the help of a custom domain, I simplified my setup. So making this run with ory platform is no longer needed. I'll close this.
