### ISSUE TITLE
Support for i18n

### ISSUE THREAD

**Issue by LandonPattison** [ory/kratos-selfservice-ui-node#199]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

When a user goes to the UI there is no way for users to see any other language besides english. 

### Describe your ideal solution

Being able to send in url parameters or get the accept-language header to display the language of the user. 

### Workarounds or alternatives

Currently we are forking the UI and adding support for i18n using the [i18next framework](https://www.i18next.com/) this framework has support for handlebars. 

### Version

latest

### Additional Context

Since I am adding this to a fork of this project, I can contribute to this project with the i18next framework. But if there is already a decision on going about this another way I'm happy to contribute.

**Comment by renom** [comment]
It'd be great to have i18n for date inputs too (date format and language)
