### ISSUE TITLE
npm package contains unnecessary files

### ISSUE THREAD

**Issue by CaptainStandby** [ory/kratos-selfservice-ui-node#239]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The package published to npm contains a lot of files, that definitely shouldn't be part of the package.

![image](https://user-images.githubusercontent.com/18215579/214289263-f07e8561-29a0-4769-ae8a-96cad25a035d.png)

Especially the `.bin/` folder containing the ory-cli bumps the package size by about 40 MiB.

### Reproducing the bug

go to https://www.npmjs.com/package/@ory/kratos-selfservice-ui-node?activeTab=explore

### Version

0.11.0-alpha.2

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

None

**Comment by Benehiko** [comment]
Yeah this needs to be cleaned up. We probably only require the `lib` and `views` directories.
