### ISSUE TITLE
UnauthorizedError: No authorization token was found

### ISSUE THREAD

**Issue by tomascharad** [ory/kratos-selfservice-ui-node#38]
**Describe the bug**

When setting up the quickstart I get the following error

![image](https://user-images.githubusercontent.com/1534092/80401068-bc57f700-8889-11ea-885c-f2074ecdb094.png)

**To Reproduce**

Run quicksart as stated in the docs: https://www.ory.sh/kratos/docs/quickstart/

**Expected behavior**

To open the login screen that appears in the docs.

**Environment**

- Version: v0.1.1-alpha.1
- Environment: Amazon Linux 2,  Docker

**Additional context**

Server logs:

![image](https://user-images.githubusercontent.com/1534092/80401303-1a84da00-888a-11ea-8e69-7bc145250356.png)

**Comment by aeneasr** [comment]
Please link to the quickstart and include the URL that you were trying to access, plus any additional steps and information (e.g. what you did before this happened).

Please use the quickstart from the stable branch, not the `next` docs.

**Comment by tomascharad** [comment]
Hi @aeneasr , I've just updated the issue, I was following this url: https://www.ory.sh/kratos/docs/quickstart/

**Comment by aeneasr** [comment]
What URL did you try to access when the error appeared?

**Comment by tomascharad** [comment]
http://ec2-54-201-140-135.us-west-2.compute.amazonaws.com:4435/dashboard

**Comment by aeneasr** [comment]
As documented [here](https://www.ory.sh/kratos/docs/quickstart/#perform-registration-logout-login), the port is 4455 :)

The 0.2 version will have an easier setup without oathkeeper!

**Comment by tomascharad** [comment]
But I think that port isn't opened

![image](https://user-images.githubusercontent.com/1534092/80402886-a566d400-888c-11ea-94b9-6e73d38f1dc5.png)

**Comment by aeneasr** [comment]
The quickstart is designed to run on localhost, but you're using it with a remote location. This can not work unless you modify the config. Please run the quickstart so that you access the URLs, as documented, via `127.0.0.1`. For deployment options it is important to at least understand the set up locally.

**Comment by tomascharad** [comment]
Ok thanks!

**Comment by tomascharad** [comment]
@aeneasr, I've made it work locally :). Many thanks.

Could you please explain me a bit further how to bring it on production? I would love to make a section on the docs detailing that process.

Many thanks.

**Comment by aeneasr** [comment]
No problem!

> Could you please explain me a bit further how to bring it on production? I would love to make a section on the docs detailing that process.

I would wait for the next release because it will make this process much easier!

**Comment by Ben-harder** [comment]
Hey there @aeneasr,
I'm trying to build off of the quickstart using the helm charts [here](https://github.com/ory/k8s/tree/master/helm/charts) but I'm running into the same issue here. If helm charts exist for the quickstart app there must be a way to not only run it locally right?

**Comment by aeneasr** [comment]
We're currently not using it ourselves so I can't confirm/deny this. If you find issues, feel free to throw up a PR! :)

**Comment by ycgambo** [comment]
same issue here

```
git clone https://github.com/ory/kratos.git
git checkout master
make quickstart-dev
```

go to `http://127.0.0.1:4455/dashboard`
```
{
  "name": "UnauthorizedError",
  "message": "No authorization token was found",
  "code": "credentials_required",
  "status": 401,
  "inner": {
    "message": "No authorization token was found"
  }
}
```

**Comment by zepatrik** [comment]
Right, I could reproduce that. Can you please open a new issue @ycgambo ?

**Comment by ycgambo** [comment]
> Right, I could reproduce that. Can you please open a new issue @ycgambo ?

sure

**Comment by licc12** [comment]
you request headers not setting `Authorization`, but you open secret check, so you get an error. you can try it like this: 
``` 
config.headers['Authorization'] = 'Bearer ' + token

# `token` is your secret
```
