### ISSUE TITLE
code bug:'JWT' should be 'jwt'

### ISSUE THREAD

**Issue by vkiller** [ory/kratos-selfservice-ui-node#58]
**Code in dashboad.ts**

`/src/routes/dashboard.ts` line 8

```
  if (config.securityMode === 'JWT') {
```
according `config.ts`,
```
export const SECURITY_MODE_JWT = 'jwt'
```
so here should be
```
  if (config.securityMode === 'jwt') {
```

https://github.com/ory/kratos-selfservice-ui-node/blob/7742d03ef93e918523e1d1b382b012c09ec753a6/src/routes/dashboard.ts#L8

otherwise there should be a issue when run jwt mode.

and since the `SECURITY_MODE_JWT` already export,why not use `SECURITY_MODE_JWT` to compare directly.

**Comment by aeneasr** [comment]
Closed via #59
