### ISSUE TITLE
Redirects and wrong headers in hydra integration branch

### ISSUE THREAD

**Issue by programmador** [ory/kratos-selfservice-ui-node#67]
I already have a working selfservice+hydra+kratos integration in my fork which is based based on @jpbogle fork.

Recently #50 was merged into a new feature branch `hydra-integration` of upstream and I've been trying to make it work in my domain-based (as opposed to port-based) environment. I've asked a question in #50 but further I've encountered bugs while debugging and decided to create this issue to prevent discussing in PR that is already merged.

So #50 contains few more bugs similar to #60 but it's behaviour is far more clear (thank You @k9ert !) - it shows errors instead of looping through redirects infinitely.

Currently I'm working on fixes so just wait for a new PR.

**Comment by programmador** [comment]
I've fixed it but now kratos always asks for login - it seems like `hydra_login_state` is either being lost or not being set.

**Comment by programmador** [comment]
> I've fixed it but now kratos always asks for login - it seems like `hydra_login_state` is either being lost or not being set.

Please correct me if I'm wrong: I think that it's because Hydra's built-in sample app which I'm using for testing always exits when I finish the consent flow and restarting it creates a new Hydra session which obviously couldn't have an active login state.

Currently I don't have an idea how to test the flow without exiting on finish. Maybe Hydra's sample app does not fit, but I didn't invent anything else currently. So for now I'll just end further debugging and push fixes which I've already done.

Please tell me if You have any idea how to test the flow without restarting Hydra session to make sure that no login flow repeat is needed.

**Comment by programmador** [comment]
BTW is there any reason why `hydra-integration` is not merged just into `master`? I've tested standalone domain-based config (kratos + selfservice only, without Hydra) - as for me everything works perfectly.

**Comment by aeneasr** [comment]
Thank you for your questions, I've (a) merged your PR and (b) commented on #50. Does this resolve your first two comments?

> Please correct me if I'm wrong: I think that it's because Hydra's built-in sample app which I'm using for testing always exits when I finish the consent flow and restarting it creates a new Hydra session which obviously couldn't have an active login state.

No, that is correct. The application terminates. We could probably add a flag `no-exit` or something similar to prevent it from doing that and just allowing you to re-do the flow.

> BTW is there any reason why hydra-integration is not merged just into master? I've tested standalone domain-based config (kratos + selfservice only, without Hydra) - as for me everything works perfectly.

Yes, this is just a workaround for now. ORY Hydra support will be implemented natively in ORY Kratos so that you don't need to write that much code and figure all of this stuff out.

**Comment by programmador** [comment]
Ok, I've got it, thank You!
