### ISSUE TITLE
Add basic customization

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos-selfservice-ui-node#72]
**Is your feature request related to a problem? Please describe.**

There should be some very basic design customization.

**Describe the solution you'd like** 

Have options to set some basic parameters like accent color and logo URI.
Provide exemplary defaults.

**Additional context**

Analog to https://github.com/ory/kratos-selfservice-ui-react/issues/1

**Comment by aeneasr** [comment]
No longer valid
