### ISSUE TITLE
UnauthorizedError: secret or public key must be provided

### ISSUE THREAD

**Issue by ykuzma1** [ory/kratos-selfservice-ui-node#88]
**Describe the bug**

I setup Oathkeeper, Kratos, and the Self Service UI using the [Zero Trust with IAP Proxy](https://www.ory.sh/kratos/docs/guides/zero-trust-iap-proxy-identity-access-proxy/) guide in our testing environment. I am able to login a user using OIDC (as reflected in the Kratos /identities API). But I get an error on the /dashboard page in the Self Service UI. Here's the error log from Self Service UI:

```
UnauthorizedError: secret or public key must be provided
  at /usr/src/app/node_modules/express-jwt/lib/index.js:105:22
  at /usr/src/app/node_modules/jsonwebtoken/verify.js:106:14
  at getSecret (/usr/src/app/node_modules/jsonwebtoken/verify.js:90:14)
  at Object.module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:94:10)
  at verifyToken (/usr/src/app/node_modules/express-jwt/lib/index.js:103:13)
  at fn (/usr/src/app/node_modules/async/lib/async.js:746:34)
  at /usr/src/app/node_modules/async/lib/async.js:1213:16
  at /usr/src/app/node_modules/async/lib/async.js:166:37
  at /usr/src/app/node_modules/async/lib/async.js:706:43
  at /usr/src/app/node_modules/async/lib/async.js:167:37
```

**To Reproduce**

Here is my current config for `kratos-selfservice-ui-node`:

```
HOST=<domain name here>

KRATOS_PUBLIC_URL=http://kratos:4433/
KRATOS_ADMIN_URL=http://kratos:4434/
BASE_URL=https://$HOST
SECURITY_MODE=jwt
JWKS_URL=http://oathkeeper:4456/.well-known/jwks.json
KRATOS_BROWSER_URL=https://$HOST/.ory/kratos/public
```

The error log makes me think it's a problem with the `JWKS_URL` setting, but it appears to be set correctly. I also can ping the `/.well-known/jwks.json` URL manually just fine.

I also further noticed that the Kratos selfservice UI `/debug` endpoint in testing *does* show an expected `Authorization` header as well as the `ory_kratos_session` cookie. So the UI does seem to be processing the auth correctly, and it seems like it could just be a display issue with the selfservice UI?

Do you guys know any better ways to debug further or have any ideas what could be causing this particular error?

**Expected behavior**

I expect to see the dashboard like I was able to do locally with the standalone Kratos quickstart.

**Environment**

Oathkeeper: v0.38.3
Kratos: v0.4.6
Self Service UI: v0.4.6

**Comment by ykuzma1** [comment]
@aeneasr @zepatrik Any updates? I hate to keep bugging you guys, but we have an app built on Kratos waiting to go into production that is held back by this issue.

**Comment by aeneasr** [comment]
I don't know what your problem is unfortunately. The [IAP guide](https://www.ory.sh/kratos/docs/guides/zero-trust-iap-proxy-identity-access-proxy/) works as far as I can tell, as I just tested it 1-1 and everything works. Without a reproducible repository, I don't think I can help here unfortunately.
