### ISSUE TITLE
Fix landing page for email verification

### ISSUE THREAD

**Issue by jaredpreston** [ory/kratos-selfservice-ui-node#97]
**Describe the bug**

When I land on the email verification page after clicking the link in the email received asking me to verify my email I see the "success" message but I also see the field to enter my email address and send the verification email again.

![image](https://user-images.githubusercontent.com/8456102/100338470-e8328b00-2fd8-11eb-853c-ff3ad1f25f32.png)

**To Reproduce**

Click on link in email received for verification.

**Expected behavior**

Land on a page that only provides a success message.

**Comment by zepatrik** [comment]
Contributions are welcome @jaredpreston :wink: 
I think you could fix that. Everything you have to do is in https://github.com/ory/kratos-selfservice-ui-node/blob/master/views/verification.hbs

**Comment by zepatrik** [comment]
Hm, actually you also have to consider https://github.com/ory/kratos-selfservice-ui-node/blob/master/src/routes/verification.ts and https://www.ory.sh/kratos/docs/reference/api#get-verification-flow

**Comment by vinckr** [comment]
This can be closed, you get redirected to the dashboard after verification.
